### ISSUE TITLE
After upgrading aos version to 6.5.5.5 LTS we are having issues with rancher node driver

### ISSUE THREAD

**Issue by med-jordan** [nutanix/docker-machine#99]
### Nutanix Cluster Information

Please provide the version of:
 - Nutanix Cluster (Prism Element / AOS) 6.5.5.5 LTS
 - Nutanix Prism Central 6.5.5.5 LTS

### Rancher Version
2.8.2

### Rancher Node Driver Version
3.6.0

### Node template

rke2 cluster

### Actual Behavior
nodes get created on nutanix aos but stuck on waiting for node ref in rancher rke2 cluster setup

### Important Factors

* #0000

**Comment by tuxtof** [comment]
Hello @med-jordan need more details, logs ...
also what is your Prism Central version ?

**Comment by tuxtof** [comment]
Not as I know

Christophe Jauffret | Principal Solutions Architect Cloud Native | Nutanix
+33 6 64 02 60 83 | ***@***.******@***.***> | @<http://twitter.com/tuxtof>tuxtof<http://twitter.com/tuxtof> | www.nutanix.com<http://www.nutanix.com/>

[Nutanix-Brand-EmailSignature-660x125]

Need a deep dive understanding of Nutanix ?
Register to Nutanix University<https://www.youtube.com/channel/UCJupSMWQRKQTvkb2CfkW0Eg>
And check out the Nutanix Bible<https://nutanixbible.com/>


From: med-jordan ***@***.***>
Date: Wednesday, 27 March 2024 at 15:27
To: nutanix/docker-machine ***@***.***>
Cc: Christophe Jauffret ***@***.***>, Comment ***@***.***>
Subject: Re: [nutanix/docker-machine] After upgrading aos version to 6.5.5.5 LTS we are having issues with rancher node driver (Issue #99)
is there any known issue with this aos version and nodedriver ? Thanks Andre — Reply to this email directly, view it on GitHub [github. com], or unsubscribe [github. com]. You are receiving this because you commented. Message ID: <nutanix/docker-machine/issues/99/2022907756@ github. com>
ZjQcmQRYFpfptBannerStart
CAUTION: External Email

ZjQcmQRYFpfptBannerEnd

is there any known issue with this aos version and nodedriver ?

Thanks
Andre

**Comment by tuxtof** [comment]
Hello @med-jordan i quickly test it on my side

pc.2022.6.0.10 + AOS 6.5.5.5 LTS
rancher 2.8.2 + node driver 3.6.0

no problem to deploy RKE1 and RKE2 cluster

![image](https://github.com/nutanix/docker-machine/assets/180613/1c8422a3-25e8-4aea-bfbb-658166dc7b0d)
